services:
  db:
    image: postgres:16
    container_name: warranty_bot_db
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
    container_name: warranty_bot
    env_file: .env
    ports:
      - "8000:80"
    depends_on:
      - db
    volumes:
      - .:/app

volumes:
  postgres_data: